import { format, parseISO } from 'date-fns'
import type { Bill, Member, Settings } from '@/types'

export async function generateBillPDF(bill: Bill, member: Member, settings: Settings): Promise<void> {
  const hostelName = settings.hostelName || 'Hostel'
  const monthLabel = format(new Date(bill.month + '-01'), 'MMMM yyyy')

  const rows = bill.lineItems.map((item) => `
    <tr>
      <td>Room ${item.roomNumber}</td>
      <td>${format(parseISO(item.periodStart), 'dd MMM')} – ${format(parseISO(item.periodEnd), 'dd MMM')} (${item.daysStayed}/${item.daysInMonth} days)</td>
      <td style="text-align:right">₹${item.roomRent.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</td>
      <td style="text-align:right">${item.roomEBShare > 0 ? '₹' + item.roomEBShare.toLocaleString('en-IN', { maximumFractionDigits: 2 }) : '—'}</td>
    </tr>
  `).join('')

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Bill – ${member.name} – ${bill.month}</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 13px; color: #111; margin: 40px; }
  h1 { font-size: 22px; margin: 0; }
  h2 { font-size: 16px; margin: 0 0 4px; color: #444; }
  .header { margin-bottom: 24px; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 20px; }
  .meta-block p { margin: 2px 0; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #f0f0f0; text-align: left; padding: 8px 10px; font-size: 12px; border-bottom: 2px solid #ccc; }
  td { padding: 7px 10px; border-bottom: 1px solid #e0e0e0; vertical-align: top; }
  .total-row { font-weight: bold; font-size: 15px; border-top: 2px solid #333; }
  .common-row td { background: #fafafa; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: bold; }
  .badge-unpaid { background: #fee2e2; color: #b91c1c; }
  .badge-paid { background: #d1fae5; color: #065f46; }
  .footer { margin-top: 32px; font-size: 11px; color: #888; border-top: 1px solid #e0e0e0; padding-top: 10px; }
</style>
</head>
<body>
<div class="header">
  <h1>${hostelName}</h1>
  ${settings.address ? `<p style="margin:2px 0;color:#666">${settings.address}</p>` : ''}
  ${settings.phone ? `<p style="margin:2px 0;color:#666">${settings.phone}</p>` : ''}
</div>

<div class="meta">
  <div class="meta-block">
    <h2>${member.name}</h2>
    ${member.phone ? `<p>${member.phone}</p>` : ''}
    ${member.email ? `<p>${member.email}</p>` : ''}
  </div>
  <div class="meta-block" style="text-align:right">
    <p><strong>Bill Period:</strong> ${monthLabel}</p>
    <p><strong>Generated:</strong> ${format(parseISO(bill.generatedAt), 'dd MMM yyyy')}</p>
    <p><span class="badge ${bill.isPaid ? 'badge-paid' : 'badge-unpaid'}">${bill.isPaid ? 'PAID' : 'UNPAID'}</span></p>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Period</th>
      <th style="text-align:right">Rent</th>
      <th style="text-align:right">Room EB</th>
    </tr>
  </thead>
  <tbody>
    ${rows}
    <tr class="common-row">
      <td colspan="3">Common EB share</td>
      <td style="text-align:right">₹${bill.commonEBShare.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</td>
    </tr>
    <tr class="total-row">
      <td colspan="3">Total</td>
      <td style="text-align:right">₹${bill.total.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</td>
    </tr>
  </tbody>
</table>

<div class="footer">
  <p>Generated by Hostel Tracker &nbsp;·&nbsp; ${format(new Date(), 'dd MMM yyyy, HH:mm')}</p>
</div>
</body>
</html>`

  const printWindow = window.open('', '_blank', 'width=800,height=900')
  if (!printWindow) {
    alert('Please allow popups to download the bill PDF.')
    return
  }
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.focus()
  setTimeout(() => {
    printWindow.print()
  }, 500)
}
